# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}
#

=head1 NAME

hydraserver:  NCM component to configure Hydra server.

=head1 DESCRIPTION

The I<hydraserver> component manages the instances of a Hydra server.

=head1 RESOURCES

No information yet :).

=head1 DEPENDENCIES

None.

=head1 BUGS

Works only with one instance at the moment.

=head1 AUTHOR

Christos Triantafyllidis <ctria@grid.auth.gr>

=head1 MAINTAINER

Christos Triantafyllidis <ctria@grid.auth.gr>

=head1 VERSION

0.0.1

=head1 SEE ALSO

ncm-ncd(1)


=cut
