#!/usr/bin/perl
use strict;
use warnings;
use Test::More tests => 8;
use Test::NoWarnings;
use Test::Quattor qw(dpm-config);
use NCM::Component::dpmlfc;
use Readonly;
use CAF::Object;
Test::NoWarnings::clear_warnings();

=pod

=head1 SYNOPSIS

This is a test suite for ncm-dpmlfc (full cconfiguration).

=cut

Readonly my $DPMLFC_CONFIG_PATH => '/software/components/dpmlfc';

Readonly my $DPM_HEAD_HOST => 'grid05.lal.in2p3.fr';
Readonly my $DPM_DISK_HOST => 'grid16.lal.in2p3.fr';

Readonly my $DPM_SYSCONFIG_FILE => '/etc/sysconfig/dpm';
Readonly my $DPNS_SYSCONFIG_FILE => '/etc/sysconfig/dpnsdaemon';
Readonly my $RFIO_SYSCONFIG_FILE => '/etc/sysconfig/rfiod';
Readonly my $SRMV1_SYSCONFIG_FILE => '/etc/sysconfig/srmv1';
Readonly my $SRMV22_SYSCONFIG_FILE => '/etc/sysconfig/srmv22';
Readonly my $DMLITE_SYSCONFIG_FILE => '/etc/httpd/conf.d/zlcgdm-dav.conf';

Readonly my $DPM_INITIAL_CONFIG =>'#
# $Id: dpm.sysconfig.mysql 9758 2013-11-28 16:54:06Z dhsmith $
#
# @(#)$RCSfile: dpm.sysconfig.mysql,v $ $Revision: 9758 $ $Date: 2013-11-28 17:54:06 +0100 (Thu, 28 Nov 2013) $ CERN/IT/ADC/CA Jean-Damien Durand
#
# should the dpm daemon run?
# any string but "yes" will equivalent to "NO"
#
RUN_DPMDAEMON="yes"
#
# should we run with another limit on the number of file descriptors than the default?
# any string will be passed to ulimit -n
#ULIMIT_N=4096
#
###############################################################################################
# Change and uncomment the variables below if your setup is different than the one by default #
###############################################################################################

ALLOW_COREDUMP="yes" 		# Line generated by Quattor

#################
# DPM variables #
#################

# - DPM Name Server host : please change !!!!!!
#DPNS_HOST=grid05.lal.in2p3.fr		# Line generated by Quattor

# - Number of DPM fast threads :
NB_FTHREADS=70 		# Line generated by Quattor

# - Number of DPM slow threads :
NB_STHREADS=20 		# Line generated by Quattor

# - DPM log file :
#DPMDAEMONLOGFILE="/var/log/dpm/log"

# - DPM configuration file :
DPMCONFIGFILE=/etc/DPMCONFIG		# Line generated by Quattor

# - Use DPM synchronous get
#export DPM_USE_SYNCGET="yes"

###################
# Globus variable #
###################

# - gridmapdir location
#GRIDMAPDIR=/etc/grid-security/gridmapdir

# - make sure we use globus pthread model
export GLOBUS_THREAD_MODEL=pthread 		# Line generated by Quattor
#DPM_HOST=grid05.lal.in2p3.fr		# Line generated by Quattor
export DPNS_HOST=grid05.lal.in2p3.fr		# Line generated by Quattor
export DPM_HOST=grid05.lal.in2p3.fr		# Line generated by Quattor
';

Readonly my $DPM_EXPECTED_CONFIG =>'# This file is managed by Quattor - DO NOT EDIT lines generated by Quattor
#
#
# $Id: dpm.sysconfig.mysql 9758 2013-11-28 16:54:06Z dhsmith $
#
# @(#)$RCSfile: dpm.sysconfig.mysql,v $ $Revision: 9758 $ $Date: 2013-11-28 17:54:06 +0100 (Thu, 28 Nov 2013) $ CERN/IT/ADC/CA Jean-Damien Durand
#
# should the dpm daemon run?
# any string but "yes" will equivalent to "NO"
#
RUN_DPMDAEMON="yes"
#
# should we run with another limit on the number of file descriptors than the default?
# any string will be passed to ulimit -n
#ULIMIT_N=4096
#
###############################################################################################
# Change and uncomment the variables below if your setup is different than the one by default #
###############################################################################################

ALLOW_COREDUMP="yes" 		# Line generated by Quattor

#################
# DPM variables #
#################

# - DPM Name Server host : please change !!!!!!
#DPNS_HOST=grid05.lal.in2p3.fr		# Line generated by Quattor

# - Number of DPM fast threads :
NB_FTHREADS=70 		# Line generated by Quattor

# - Number of DPM slow threads :
NB_STHREADS=20 		# Line generated by Quattor

# - DPM log file :
#DPMDAEMONLOGFILE="/var/log/dpm/log"

# - DPM configuration file :
DPMCONFIGFILE=/etc/DPMCONFIG		# Line generated by Quattor

# - Use DPM synchronous get
#export DPM_USE_SYNCGET="yes"

###################
# Globus variable #
###################

# - gridmapdir location
#GRIDMAPDIR=/etc/grid-security/gridmapdir

# - make sure we use globus pthread model
export GLOBUS_THREAD_MODEL=pthread 		# Line generated by Quattor
#DPM_HOST=grid05.lal.in2p3.fr		# Line generated by Quattor
export DPNS_HOST=grid05.lal.in2p3.fr		# Line generated by Quattor
export DPM_HOST=grid05.lal.in2p3.fr		# Line generated by Quattor
';


Readonly my $DPNS_INITIAL_CONFIG => '
';

Readonly my $DPNS_INITIAL_CONFIG => '
';

Readonly my $RFIO_INITIAL_CONFIG => '
';

Readonly my $RFIO_INITIAL_CONFIG => '
';

Readonly my $SRMV1_INITIAL_CONFIG => '
';

Readonly my $SRMV1_INITIAL_CONFIG => '
';

Readonly my $SRMV22_INITIAL_CONFIG => '
';

Readonly my $SRMV22_INITIAL_CONFIG => '
';

Readonly my $DMLITE_INITIAL_CONFIG => '
';

Readonly my $DMLITE_INITIAL_CONFIG => '
';


$CAF::Object::NoAction = 1;

my $cmp = NCM::Component::dpmlfc->new('dpmlfc');
my $config = get_config_for_profile("dpm-config")->getElement($DPMLFC_CONFIG_PATH)->getTree();

set_file_contents($DPM_SYSCONFIG_FILE, $DPM_INITIAL_CONFIG);
set_file_contents($DPNS_SYSCONFIG_FILE, $DPNS_INITIAL_CONFIG);
set_file_contents($RFIO_SYSCONFIG_FILE, $RFIO_INITIAL_CONFIG);
set_file_contents($SRMV1_SYSCONFIG_FILE, $SRMV1_INITIAL_CONFIG);
set_file_contents($SRMV22_SYSCONFIG_FILE, $SRMV22_INITIAL_CONFIG);
set_file_contents($DMLITE_SYSCONFIG_FILE, $DMLITE_INITIAL_CONFIG);

$cmp->configureNode($DPM_HEAD_HOST,$config);

my $fh = get_file($DPM_SYSCONFIG_FILE);
ok(defined($fh), "$DPM_SYSCONFIG_FILE was opened (1)");
is("$fh",$DPM_EXPECTED_CONFIG,"$DPM_SYSCONFIG_FILE has expected contents (1)");
$fh->close();

Test::NoWarnings::had_no_warnings();
