# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}
#

=head1 NAME

lcgmonjob: NCM component to configure lcg-mon-job-status daemon

=head1 DESCRIPTION

The I<lcgmonjob> component manages the configuration for the
lcg-mon-job-status daemon.  It essentially just links the
init.d script to the correct location and ensures that the
daemon is restarted when the configuration changes. 

=head1 RESOURCES

=head2 EDG_LOCATION

The location of the EDG software.

=head2 LCG_LOCATION

The location of the LCG software.

=cut
