# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}
#

=head1 NAME

yaim_usersconf: NCM component to write C<< users.conf >> and C<< groups.conf >>
files used by YAIM to generate grid-mapfiles.

=head1 DESCRIPTION

The I<yaim_usersconf> component writes the C<< users.conf >> and C<< groups.conf >>
files used by YAIM. The exact locations should be specified in the CDB
structure at C<< /software/components/yaim_usersconf/users_conf_file >> and
C<< /software/components/yaim_usersconf/groups_conf_file >>.

=head1 RESOURCES

=over

=item * C<< /system/vo/<VO-name>/gridusers >> : list

A list of nlists, where each element specifies a username and an (optional)
flag to describe the role of the user.

The component will iterate over this list, writing an entry in C<< users.conf >>
for each element that has a corresponding user on the system.

=item * C<< /system/vo/<VO-name>/gridgroups >> : list

A list of nlists, where each element specifies a VOMS path and an (optional)
flag to describe the role.

The component will iterate over this list, writing an entry in C<< groups.conf >>
for each element that has a corresponding group on the system.

=back

=cut

