# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}
#

=head1 NAME

ncm-lbconfig: NCM lbconfig component 

=head1 DESCRIPTION

The I<ncm-lbconfig> component manages the configuration file of the WP1
lbserver.  It creates the /opt/edg/etc/edg_wl_query_index file with
the values saved in the machine profile. 

=head1 RESOURCES

=head2 configFile (edg_wl_query_index.conf)

The name of the configuration file.  It will be created in the
location EDG_LOCATION/etc.  

=head2 type (system)

The type of the resource.

=head2 owner

The owner. 

=head2 location

The location. 

=head2 destination

The destination. 

=cut
