# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}
#

=begin comment

Be sure to put a blank line before and after every formatting command

=end comment

=head1 NAME

dcache : NCM component to manage dcache configuration.

=head1 DESCRIPTION

This component allows to manage configuration of dcache. For some info, check the README file.

=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Stijn.De.Weirdt@cern.ch

=head1 MAINTAINER

Stijn.De.Weirdt@cern.ch

=head1 VERSION

4.0.0

=head1 SEE ALSO

ncm-ncd(1)


=cut

