# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}
#

=head1 NAME

vomsclient: NCM component to manage VOMS client configuration

=head1 DESCRIPTION

The I<vomsclient> component manages the configuration for the VOMS
clients.  This writes the VOMS server certificates to the vomsCertsDir
directory and the VOMS server parameters to the vomsServersDir
directory. 

=head1 EXAMPLE

    "/software/components/vomsclient/vos" = npush("somevo.example.org",
        list(dict(
            "host", "vo.somevo.example.org",
            "port", "20000",
            "cert", <<EOF)));
            ----BEGIN CERTIFICATE----
            ... encoded binary info ...
            ----END CERTIFICATE----
        EOF

=cut
