# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}
#

=head1 NAME

gold: NCM component to configure gold client and server.

=head1 DESCRIPTION

The I<gold> component manages the configuration for the GOLD client
 and server. By default the configuration file(s) resides in
/usr/local/gold/etc.  



=cut
