# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}
#

=begin comment

Be sure to put a blank line before and after every formatting command

=end comment

=head1 NAME

dpmlfc : NCM component to manage DPM and LFC configuration.

=head1 DESCRIPTION

This component allows to manage configuration of LCG DPM and LFC services. Currently, it allows to manage the configuration of all daemons.

Component dpmlfc requires that the DPM and/or LFC configuration describes all nodes participating to the service and their respective 
role (in term of daemon running on each node). Each daemon/host combination is called a daemon instance in this documentation.

Using the whole DPM and/or LFC description, dpmlfc takes care of action needed on every node to configure it as requested 
(you MUST use the same configuration description on every node participating to DPM and/or LFC). This includes restarting 
a service after configuration changes if needed.

In addition to daemon instance options, there are some global options (one set for DPM and one set for LFC). 
A subset of these global options are used to describe database connection but database is not created/managed by this component.

Following sections describe each option by group of related options.

=head1 GLOBAL OPTIONS (DPM and LFC)

DPM and LFC accept the same global options but there is a separate set for each one. Replace 'PRODUCT' by 'dpm' or 'lfc'.

=head2 /software/components/dpmlfc/options/PRODUCT/accessProtocols : list (optional, DPM only)

List of access protocols supported on disk servers. Supported protocols are : https, gsiftp, rfio, xroot.
Note that xrootd configuration itself, including the DPM/Xrootd plug-in, must be configured with
ncm-xrootd.

Default: None (default configuration provided by RPM will be used)

=head2 /software/components/dpmlfc/options/PRODUCT/controlProtocols : list (optional, DPM only)

List of control protocols supported. Supported protocols are : srmv1, srmv2, srmv2.2.

Default: None (default configuration provided by RPM will be used)

=head2 /software/components/dpmlfc/options/PRODUCT/gridmapfile

This option defines the local gridmap file used by products daemons. 

Default: None (default configuration provided by RPM will be used)

=head2 /software/components/dpmlfc/options/PRODUCT/gridmapdir

This option defines the gridmap dir used by products daemons. 

Default: None (default configuration provided by RPM will be used)

=head2 /software/components/dpmlfc/options/PRODUCT/group

This option defines the userid used by product daemons. 

Default: None (default configuration provided by RPM will be used)

=head2 /software/components/dpmlfc/options/PRODUCT/user

This option defines the userid used by product daemons. 

Default: dpmmgr for DPM, lfcmgr for LFC


=head1 DATABASE CONNECTION OPTIONS (DPM and LFC)

DPM and LFC accepts the same set of options to describe the database connection. In the following options name, 
replace 'PRODUCT' by either 'dpm' or 'lfc'. Both sets can coexist.

=head2 /software/components/dpmlfc/options/PRODUCT/db/configfile

This option defines the file used to keep track of database connection information. This file will be owned by the userid used to run daemons and only this user will have access to this file.

Default : /etc/DPMCONFIG for DPM, /etc/NSCONFIG for LFC

=head2 /software/components/dpmlfc/options/PRODUCT/db/infoFile (string, optional)

Name (without path) of the file containing connection information to DPM DB to be used by GIP to collect information about DPM.
This file will be owned and accessible only by GIP user.

This file will not be created if 'infoUser' is not defined.

Default : DPMINFO for DPM, LFCINFO for LFC.

=head2 /software/components/dpmlfc/options/PRODUCT/db/infoPwd (string, optional)

Password for database connection account used by GIP to collect information about DPM

Default : generated password. It is recommended to use this default value (password changed at each run).

=head2 /software/components/dpmlfc/options/PRODUCT/db/infoUser (string, optional)

Username for database connection account used by GIP to collect information about DPM

Default : None

=head2 /software/components/dpmlfc/options/PRODUCT/db/password (string, required)

This option defines the password used to connect to the database.

Default : none

=head2 /software/components/dpmlfc/options/PRODUCT/db/server (string, optional)

This option defines the server running the database. This component checks that
DPM and LFC database server run on different node (DPNS and LFC use the same database name). 
'localhost' is considered different as DPNS and LFC are not allowed to run on the same node. 

Default : localhost.

=head2 /software/components/dpmlfc/options/PRODUCT/db/user

This option defines the userid used to connect to the database.

Default : userid used to run daemons


=head1 DAEMON INSTANCE OPTIONS (DPM and LFC)

Each daemon instance is described under the relevant subset of the component configuration ('dpm', 'dpns', 'srmv1', srmv22', ...).
See the schema or the RESOURCES section below for the list of all the daemons/services that can be managed by the component.

For each daemon/service, the configuration is described in a nlist where the key is host name for the instance and the value is a
nlist of the following options. Configuration options can be different for each host running an instance of the service but it is
generally not sensible not to use the same value for each host.

Every daemon instance description accepts a subset of the following options 
(see the actual subset accepted by every daemon under RESOURCES below).

=head2 allowCoreDump: boolean (optional)

'allowCoreDump' allows to explicitly enable/disable creation of a core dump in the event of a daemon crash.

Default: use daemon default (see documentation)

=head2 logfile: string (optional)

'logfile' option is the name of the logfile used by the daemon instance. Generally, each daemon has a dedicated directory under /var/log, where the actual log file is rotated. This option is accepted by every type of daemon.

Default : use daemon default (see documentation).

=head2 port: long (optional)

'port' allows to specify a non standard port for the daemon.

Default : default service port (see documentation or 'man service_name').

=head2 threads : long (optional)

Number of threads to use.

Default : default service port (see documentation or 'man service_name').

=head2 maxOpenFiles : long (optional)

Maximum number of open files (used as input to ulimit).

Default : default service port (see documentation or 'man service_name').

=head2 requestMaxAge: string (optional, 'dpm' daemon only)

'requestMaxAge' allows to configure automatic purging of DPM request database, based on request age. It defines
the maximum lifetime allowed for a request before it is removed from the request database. This must be a number
optionally followed by 'y' (year), 'm' (month), 'd' (day), 'h' (hour). If no unit is specified, the number is
interpreted as seconds.

Default: by default automatic purging is disabled

=head2 fastThreads : long (optional, 'dpm' daemon only)

Number of threads to use for short operations

Default : default service configuration (see documentation or 'man service_name').

=head2 slowThreads : long (optional, 'dpm' daemon only)

Number of threads to use for long operations

Default : default service configuration (see documentation or 'man service_name').

=head2 useSyncGet : boolean (optional, 'dpm' daemon only)

Use synchronous get operation when querying the namespace.

Default : default service configuration (see documentation or 'man service_name').

=head2 readonly : boolean (optional, dpns and lfc only)

Configure a readonly DPNS

Default : default service configuration (see documentation or 'man service_name').

=head2 portRange : string (optional, rfio or gsiftp)

TCP port range to use for transfers.

Default : default service configuration (see documentation or 'man service_name').

=head2 startupOptions : string (optional, rfio or gsiftp)

Daemon options to use at startup.

Default : default service configuration (see documentation or 'man service_name').

=head2 disableAutoVirtualIDs : boolean (optional, lfc only)

Disable automatic creation of virtual IDs.

Default : default service configuration (see documentation or 'man service_name').



=head1 VO OPTIONS (DPM and LFC) : /software/components/dpmlfc/vos

VO-related options described each VO that must be configured to get access to DPM or LFC namespace. This includes creating VO home directory and setting correct permissions.

VO-related options are stored under /software/components/dpmlfc/vos, which is a nlist with one entry per VO. nlist key is the VO name. Value is a nlist describing VO properties.

=head2 /software/components/dpmlfc/vos/VONAME/gid

This property specifies virtual GID to associate with the VO. Default is normally appropriate

Default : auto-generated virtual GID.


=head1 POOL OPTIONS (DPM)

=head2 /software/components/dpmlfc/pool

See schema.


=head1 DEPENDENCIES

None.

=head1 BUGS

None known.

=head1 AUTHOR

Michel Jouvin <jouvin@lal.in2p3.fr>

=head1 MAINTAINER

Michel Jouvin <jouvin@lal.in2p3.fr>

=head1 VERSION

1.9.1

=head1 SEE ALSO

ncm-ncd(1)


=cut

